### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by demhademha** [DragonBuild/DragonBuild#12]
Hi, I understand this project is in its infancy, but will ios support eventually be added?
Thanks

**Comment by KritantaDev** [comment]
This tool already supports iOS, and a recent change to the installer script should make it fully compatible.

**Comment by KritantaDev** [comment]
I'm leaving this issue open until I test it myself, but it reportedly works.

**Comment by KritantaDev** [comment]
Working :)
