### ISSUE TITLE
calling of setupSSHKey() in dragon slightly broken

### ISSUE THREAD

**Issue by ItHertzSoGood** [DragonBuild/DragonBuild#28]
**will pr with a fix at some point**

SSH Passwordless Authentication prompt (from setupSSHKey()) will repeatedly be called whenever you run `dragon do` until you decline, whether you set it up or not

**Comment by KritantaDev** [comment]
The interactive ssh prompt stuff (the entire bash thing, too) needs to be ported to python, this kind of complex handling is going to crash and burn in bash, I'll hop on that

**Comment by ItHertzSoGood** [comment]
Fair enough. I was just going to use a more robust method of detecting it, e.g. create `~/.dragonbuild/state/.sshAlreadySetUp` and make an if statement to see if that exists before doing anything, and remove it if the phoneip is reset

**Comment by KritantaDev** [comment]
I’m going to close this as the python port is nearing fruition.
