### ISSUE TITLE
`dragon clean` leaves build.ninja file

### ISSUE THREAD

**Issue by ItHertzSoGood** [DragonBuild/DragonBuild#29]
If you run `dragon clean` in any project, a build.ninja file appears regardless of your preference

**Comment by KritantaDev** [comment]
The entire “system” regarding these files has been rewritten since this issue was created, can you verify this bug still occurs?

**Comment by ItHertzSoGood** [comment]
Still seems to be happening after `dragon update`. [Screenshot](https://cdn.quiprr.dev/TPAhErwN.png)

**Comment by KritantaDev** [comment]
edge case issue with a very convoluted solution that will worsen codebase. Waiting for the python rewrite.
