### ISSUE TITLE
error: -fobjc-arc is not supported on platforms using the legacy runtime

### ISSUE THREAD

**Issue by AirKetchPLAYZ** [DragonBuild/DragonBuild#31]
Cannot build anything. not even the example project
When i run the install script it cannot install ninja or ldid.
Ninja is the wrong package name, so i just manually installed with the right name, ninja-build. I couldn't find ldid
Anyway when i try to build anything, even the example project, I get that error that is in the title

**Comment by KritantaDev** [comment]
This is an issue with toolchains, please follow the instructions in the readme.
