### ISSUE TITLE
DragonBuild not working on macOS Catalina (10.15.4) when building from a Theos Project

### ISSUE THREAD

**Issue by cbyrne** [DragonBuild/DragonBuild#7]
![image](https://user-images.githubusercontent.com/31479541/82749750-4f118600-9da3-11ea-8415-5ce728ff4ad7.png)
These errors get printed when running any ``dragon`` subcommand (v, h, etc.)

I use macOS' included ZSH shell, default Terminal App

**Comment by KritantaDev** [comment]
Did you remove all previous traces of the non-v1 project?

**Comment by cbyrne** [comment]
Yep, this is a clean-install of macOS Catalina that I did a few days ago. Only installed DragonBuild this morning using the install script in the README

**Comment by KritantaDev** [comment]
What's the output of `cat ~/.zshrc`?

**Comment by cbyrne** [comment]
![image](https://user-images.githubusercontent.com/31479541/82749853-fdb5c680-9da3-11ea-83f4-ad52bf38e602.png)

**Comment by cbyrne** [comment]
After further inspection, deleting the last 3 lines of the ``source ~/.dragonbuild/internal/environment`` seems to have done the trick. Not sure why it's there 3 times, weird!

**Comment by KritantaDev** [comment]
That's weird, I'm going to leave this issue open in case someone else happens to have this happen. It could be an issue with the install script

**Comment by cbyrne** [comment]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/31479541/83396861-89f36980-a3f4-11ea-874d-79c96ff9c04a.png">
This is the only thing I can see, is ``.profile`` loaded by zsh? If so, `source` is running two times:

 - Once by .zshrc
 - Once by .profile

**Comment by cbyrne** [comment]
Nope, zsh loads .zprofile

Weird, I'm installing it on another computer as we speak and I'll see what happens

**Comment by KritantaDev** [comment]
I removed the (probably stupid) environment variable dependency. You shouldn't need anything in your profile when installing the latest version.
